#!/bin/bash

# Init at StartUP Initialize MySQL data directory
#mysql_install_db --user=mysql

# wait for mysql server to start (max 120 seconds)
#mysqladmin -uroot status

mkdir /init_confdir

cp -r /etc/my.cnf.d/*  /init_confdir
#cp -r /var/lib/mysql/* /init_datadir

echo "" > /var/log/mariadb/mariadb.log

exit 0
