#!/bin/bash

# Initialize MySQL data directory
if [ ! -d /var/lib/mysql/mysql ]; then
	mysql_install_db --user=mysql
fi

# wait for mysql server to start (max 120 seconds)
#mysqladmin -uroot status

#echo "Populating mysql database..."

/usr/bin/mysqld_safe --datadir='/var/lib/mysql' &

sleep 10
echo "Initialize Root password :"
echo -e "\n\nchangeme\nchangeme\n\n\nn\n\n\n" | mysql_secure_installation && history -c

mkdir /init_datadir

cp -r /var/lib/mysql/* /init_datadir

/usr/bin/mysqladmin -u root --password=changeme shutdown

sleep 5

echo ""
echo "*************************************************************************"
echo "* Please login to the mysql server and change the root password         *"
echo "* user: root                                                            *"
echo "* password: changeme                                                    *"
echo "*                                                                       *"
echo "*   CREATE DATABASE db_name;                                            *"
echo "*   CREATE USER 'db_user'@'%' IDENTIFIED BY 'db_password';              *"
echo "*   GRANT ALL ON DATABASE.* to 'db_user'@'%';                           *"
echo "*   FLUSH PRIVILEGES;                                                   *"
echo "*************************************************************************"
echo ""

exit 0